const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const icons={rock:'✊',paper:'✋',scissors:'✌️'},beats={rock:'scissors',paper:'rock',scissors:'paper'};
let running=false,enemies=[],score=0,popped=0,startTime=0,lastSpawn=0,raf,player='JOGADOR';
const arena=$('#arena');

function screen(id){$$('.screen').forEach(s=>s.classList.remove('active'));
$('#'+id).classList.add('active');
if(id==='home')renderBoard('#homeBoard')}function scores(){return JSON.parse(localStorage.getItem('jokenpoBalloonScores')||'[]')}function safe(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function renderBoard(target){const data=scores().slice(0,5);
$(target).innerHTML=data.length?data.map((x,i)=>`<li><b>#${i+1}</b><span>${safe(x.name)}</span><strong>${x.score}</strong></li>`).join(''):'<li class="empty">SEJA O PRIMEIRO CAMPEÃO!</li>'}
$('#playBtn').onclick=start;
$('#againBtn').onclick=()=>screen('home');
$$('.controls button').forEach(b=>b.onclick=()=>shoot(b.dataset.move));
addEventListener('keydown',e=>{if(e.repeat)return;
const map={'1':'rock','2':'paper','3':'scissors'};
if(map[e.key])shoot(map[e.key])});

function start(){player=$('#playerName').value.trim().toUpperCase()||'JOGADOR';
score=popped=0;
enemies.forEach(e=>e.el.remove());
enemies=[];
running=true;
startTime=performance.now();
lastSpawn=-9999;
loop.last=0;
$('#score').textContent='0000';
$('#level').textContent='1';
screen('game');
raf=requestAnimationFrame(loop)}function difficulty(now){const elapsed=(now-startTime)/1000;
return{level:1+Math.floor(elapsed/15),speed:85+elapsed*2.7,interval:Math.max(480,1450-elapsed*18)}}function spawn(now){const types=Object.keys(icons),type=types[Math.floor(Math.random()*3)],el=document.createElement('div');
el.className='balloon '+type;
el.textContent=icons[type];
arena.appendChild(el);
enemies.push({type,el,y:-100});
lastSpawn=now}
function loop(now){if(!running)return;
const d=difficulty(now),dt=Math.min(.035,(now-(loop.last||now))/1000);
loop.last=now;
$('#level').textContent=d.level;
if(now-lastSpawn>d.interval)spawn(now);
for(const enemy of enemies){enemy.y+=d.speed*dt;
enemy.el.style.top=enemy.y+'px';
if(enemy.y>arena.clientHeight-105){gameOver();
return}}raf=requestAnimationFrame(loop)}function updateScore(){const value=Math.abs(score).toString().padStart(4,'0');
$('#score').textContent=(score<0?'-':'')+value}function shoot(type){if(!running)return;
const button=$(`.controls [data-move="${type}"]`);
button.classList.add('active');
setTimeout(()=>button.classList.remove('active'),110);
const shot=document.createElement('div');
shot.className='shot '+type;
shot.textContent=icons[type];
arena.appendChild(shot);
setTimeout(()=>shot.remove(),720);
const target=enemies.filter(e=>e.y>40).sort((a,b)=>b.y-a.y)[0];
if(!target){setTimeout(()=>{if(!running)return;
score-=50;
updateScore();
message('ERROU O ALVO! -50')},700);
return}
if(beats[type]===target.type){const idx=enemies.indexOf(target);
if(idx>=0)enemies.splice(idx,1);
target.el.classList.add('pop');
setTimeout(()=>target.el.remove(),300);
popped++;
score+=150;
updateScore();
message('POW! +150')}else if(type===target.type){score-=50;
updateScore();
message('EMPATE! -50')}else{score-=100;
updateScore();
message('PERDEU! -100')}}
function message(text){const m=$('#message');
m.textContent=text;
m.classList.remove('show');
void m.offsetWidth;
m.classList.add('show')}function gameOver(){running=false;
cancelAnimationFrame(raf);
const level=difficulty(performance.now()).level;
let board=scores();
board.push({name:player,score,date:Date.now()});
board.sort((a,b)=>b.score-a.score);
localStorage.setItem('jokenpoBalloonScores',JSON.stringify(board.slice(0,10)));
$('#finalScore').textContent=score;
$('#finalLevel').textContent=level;
$('#popped').textContent=popped;
renderBoard('#finalBoard');
screen('over')}renderBoard('#homeBoard');
